services:
  backend:
    build: 
      context: ./chatbot
      dockerfile: Dockerfile
    container_name: chatbot-backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build: 
      context: ./terminal
      dockerfile: Dockerfile
    container_name: terminal-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network

  training-service:
    build: 
      context: ./training
      dockerfile: Dockerfile
    container_name: chatbot-training
    networks:
      - app-network
    stdin_open: true
    tty: true

networks:
  app-network:
    driver: bridge
