services:
  backend:
    build: 
      context: .
      dockerfile: chatbot/Dockerfile
    container_name: chatbot-backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build: 
      context: ./terminal
      dockerfile: Dockerfile
    container_name: terminal-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network

  training-service:
    build: 
      context: .
      dockerfile: training/Dockerfile
    runtime: nvidia
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - NVIDIA_VISIBLE_DEVICES=0
      - CUDA_VISIBLE-DEVICES-0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./training/train.py:/train.py
      - ./training/config.cfg:/config.cfg
      - ./models:/models    
    container_name: chatbot-training
    networks:
      - app-network
    stdin_open: true
    tty: true

networks:
  app-network:
    driver: bridge

  default:
    driver: bridge
