version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: flask-backend
    ports: 
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: angular-frontend
    ports: 
      - "4200:80"
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge